module.exports = {
  adapt: require('./adapt').default,
  adjacent: require('./adjacent').default,
  brightness: require('./brightness').default,
  complementary: require('./complementary').default,
  contrast: require('./contrast').default,
  contrastRatio: require('./contrastRatio').default,
  convert: require('./convert').default,
  difference: require('./difference.js'),
  fade: require('./fade.js'),
  greyscale: require('./greyscale.js'),
  hue: require('./hue.js'),
  invert: require('./invert.js'),
  invertLightness: require('./invertLightness.js'),
  mid: require('./mid.js'),
  multiply: require('./multiply.js'),
  saturation: require('./saturation.js'),
  sepia: require('./sepia.js'),
  shade: require('./shade.js'),
  temperature: require('./temperature.js'),
  tetrad: require('./tetrad.js'),
  triad: require('./triad.js'),
  uniformComplementary: require('./uniformComplementary.js'),
  uniformTriad: require('./uniformTriad.js'),
  uniformTetrad: require('./uniformTetrad.js')
}
