module.exports = {
  adapt: require('./adapt').default,
  adjacent: require('./adjacent').default,
  brightness: require('./brightness').default,
  complementary: require('./complementary').default,
  contrast: require('./contrast').default,
  contrastRatio: require('./contrastRatio').default,
  convert: require('./convert').default,
  difference: require('./difference').default,
  fade: require('./fade').default,
  greyscale: require('./greyscale').default,
  hue: require('./hue').default,
  invert: require('./invert').default,
  invertLightness: require('./invertLightness').default,
  mid: require('./mid').default,
  multiply: require('./multiply').default,
  saturation: require('./saturation').default,
  sepia: require('./sepia').default,
  shade: require('./shade').default,
  temperature: require('./temperature').default,
  tetrad: require('./tetrad').default,
  triad: require('./triad').default,
  uniformComplementary: require('./uniformComplementary').default,
  uniformTriad: require('./uniformTriad').default,
  uniformTetrad: require('./uniformTetrad').default
}
