module.exports = {
  adapt: require('./adapt.js'),
  adjacent: require('./adjacent.js'),
  brightness: require('./brightness.js'),
  complementary: require('./complementary.js'),
  contrast: require('./contrast.js'),
  contrastRatio: require('./contrastRatio.js'),
  convert: require('./convert.js'),
  difference: require('./difference.js'),
  fade: require('./fade.js'),
  greyscale: require('./greyscale.js'),
  hue: require('./hue.js'),
  invert: require('./invert.js'),
  invertLightness: require('./invertLightness.js'),
  mid: require('./mid.js'),
  multiply: require('./multiply.js'),
  saturation: require('./saturation.js'),
  sepia: require('./sepia.js'),
  shade: require('./shade.js'),
  temperature: require('./temperature.js'),
  tetrad: require('./tetrad.js'),
  triad: require('./triad.js')
};
